config/routes.rb
Rails.application.routes.draw do
  get 'users/bank'

  get "pages/home"

  get 'pages/about'

  get 'pages/contact'

  root 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def Home
    render text: 'This will be the home page'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def bank
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<hr/>
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", pages_about_path %></li>
      <li><%= link_to "Contact", pages_contact_path    %></li>
      <li><a href="https://github.com/nand09">Fernando Osorto</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<ul class="nav nav-pills">
  <li role="presentation" class="active"><%= link_to "Home", root_path %></li>
  <li role="presentation"><%= link_to "About", pages_about_path %></li>
  <li role="presentation"><%= link_to "Contact", pages_contact_path %></li>
</ul>
<br/ color="black">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BYB Accountant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
<%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>App Created using Ruby on Rails</h1>
<div class="jumbotron"
    <p>This app allows an user to keep track of daily expenses</p>
</div>

app/views/pages/contact.html.erb
<h1>Information about developer.</h1>
<div class='jumbotron'
<p>App made by <%= link_to "Fernando Osorto","https://www.linkedin.com/in/fernando-osorto-088993122"%>.</p>
<br>
<p>Look at my other projects on <%=link_to "Github","https://github.com/nand09"%>.</p>
</div>

app/views/pages/home.html.erb
<h1>Be your own accountant!</h1>
<div class="jumbotron"
    <p>Keep track of your daily expenses.</p>
    <br>
    <p>Start  <%= link_to "Here", users_bank_path %> </p>
</div>

app/views/users/bank.html.erb
<div class="center jumbotron">
    <h2>Add accounts to keep track of your finances.</h2>
</div>
<form class="form-inline">
  <div class="form-group">
    <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <input type="text" class="form-control" id="exampleInputAmount" placeholder="Amount">
      <div class="input-group-addon">.00</div>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Add account</button>
</form>